### ISSUE TITLE
support metacity-theme-3.xml

### ISSUE THREAD

**Issue by rilian-la-te** [mate-desktop/marco#105]
I think in windows with Global Dark Theme enabled must have dark header (if theme supports). Mutter do this.

Screen from Mutter:
![2014-05-24-161117_1366x768_scrot](https://cloud.githubusercontent.com/assets/1329638/3074086/85d233ce-e323-11e3-850c-f87db8f95b9c.png)

And from Marco:
![2014-05-24-161152_1366x768_scrot](https://cloud.githubusercontent.com/assets/1329638/3074087/8cadae3a-e323-11e3-8c7b-8afc7bb832bb.png)
##

**Comment by nana-4** [comment]
Hi,

Since MATE has migrated to GTK3, I think Marco needs to support `metacity-theme-3.xml` format to fix this issue. `gtk:custom(name,fallback)` works only in `metacity-theme-3.xml`, but dosen't work in `metacity-theme-2.xml`.

By the way, I honestly prefer Mutter over Metacity/Marco. Because Mutter allows more easier theming and easier resizing window. I personally want to see MATE migrate to Mutter as the default window manager. Just as GNOME 3 and Budgie did. But it's just my opinion. :)

Thanks.

**Comment by monsta** [comment]
@rilian-la-te: so, this is more about adding `metacity-theme-3.xml` support in general?

**Comment by rilian-la-te** [comment]
Yes))))

**Comment by monsta** [comment]
Ok, renamed

**Comment by muktupavels** [comment]
> By the way, I honestly prefer Mutter over Metacity/Marco. Because Mutter allows more easier theming and easier resizing window. I personally want to see MATE migrate to Mutter as the default window manager. Just as GNOME 3 and Budgie did. But it's just my opinion. :)

@nana-4 Metacity != Marco... Metacity since 3.20 version by default use GTK+ theme just like Mutter.

**Comment by nana-4** [comment]
I'm sorry... My apologies for the thoughtless remark.
