### ISSUE TITLE
Black flickering opening windows

### ISSUE THREAD

**Issue by introlinux** [mate-desktop/marco#325]
I don't know if this is the right site for this issue but anyway I comment.
A black flickering appears when I open any program. It is almost imperceptible, but when you realize it is very annoying.
It is not a hardware problem, it occurs in all PCs I tested. And the system is Siduction Linux distribution with MATE 1.16.2 
I tried to change GTK themes and MARCO composition options, but no luck.

**Comment by qazwsxedcgit** [comment]
Can confirm. What seems to happen is that each window is drawn with a black background first, and then the window contents is rendered on top of that. What should be happening is that the window is rendered completely first, and only then shown to the user.

This flicker is very noticeable and very distracting. It shows up in a default installation of Debian 9.0 Stretch with MATE desktop, which is terrible advertising ;-(

This is also an accessibility issue since flicker like that can precipitate epileptic attacks. Can I suggest that it is prioritized accordingly?

**Comment by raveit65** [comment]
Does the issue still exists?

**Comment by raveit65** [comment]
No answer from reporter since 4 years.

**Comment by qazwsxedcgit** [comment]
Yes, the issue still exists.
