### ISSUE TITLE
Alt+tab: icons are too small

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/marco#333]
#### Actual behaviour
I use Marco with enabled compositor and with disabled windows thumbnails. When I press Alt+tab to switch windows, I see windows icons — they are too small and it is hard to recognize applications.

#### Expected behaviour
Windows icons should be bigger, such as in Metacity.

#### Package version
marco 1.18.1

**Comment by gabrielschulhof** [comment]
I think the size of the Alt+Tab switcher should be based on the DPI of the font used for the window title, which is shown under the icon list. I set my DPI to 192, and the icons are tiny, and all I get for the window title is ellipses.

I really need to know the title of each window as I Alt+Tab because I usually have, like, 23 text editor windows open, each showing a different file name in the title.

**Comment by gabrielschulhof** [comment]
marco 1.18.2 here.

**Comment by trongthanh** [comment]
Any progress or feedback please? This is the last thing I'm not happy about Marco atm.

Sorry to raise voice but I want this issue to get some attention.

**Comment by osch** [comment]
On my screen the icons are huge now (96dpi). Ist it possible to reduce the icon size by configuration somehow?

**Comment by sc0w** [comment]
@osch you can open new issue with screenshot

**Comment by osch** [comment]
@sc0w OK, see #479
