### ISSUE TITLE
Web site is not working

### ISSUE THREAD

**Issue by ne-vlezay80** [mate-desktop/marco#377]
The project site is redirect from: http://ivrn.net/block.html?reason=5

**Comment by flexiondotorg** [comment]
No idea what you're reporting, but the mate-desktop.org site is working.

**Comment by lukefromdc** [comment]
The linked site is in another language, I could not make heads or tails of it. I could not tell if it was a local ISP blocking something, a governmental block-or something else. Due to that I immediately closed all browser windows, which in my setup also unmounts the tmpfs I use as a .mozilla directory.  This as a security precaution.

For future reference, we need to consider that a possible way to attack MATE would be to attack a user's computer, via an issue linking to a malicious website using cross-paltform exploits to install a cross-platform payload such as a keylogger. Fortunately, I never permit an unknown website to run Javascript.
