### ISSUE TITLE
Workspace now doesn't show up in context menu

### ISSUE THREAD

**Issue by Ryuno-Ki** [mate-desktop/marco#51]
Workspace switcher 1.6.0

        $ mate-about --version
        MATE Desktop Environment 1.6.0
        $ uname -a
        Linux rotfisch 3.5.0-32-generic #53~precise1-Ubuntu SMP Wed May 29 20:33:37 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

When you rightclick the workspace switcher and name your workspaces, they don't show up in context menu of windows ("Move to other workspace").

**Comment by monsta** [comment]
Not reproducible in Debian Testing with MATE 1.10. All workspace name changes are properly reflected in the window's menu, without any delays. If the issue isn't confirmed for 1.10 I'll close it.

**Comment by Ryuno-Ki** [comment]
Running Mate 1.8.1 here on Sabayon.

**Comment by Ryuno-Ki** [comment]
Attached a screenshot to clarify what I am referring to.
![workspace switcher](https://cloud.githubusercontent.com/assets/3097194/10144916/81e94db6-6620-11e5-8e04-847a9dfec65c.png)

**Comment by raveit65** [comment]
Works out of box here in fedora-22 with mate-1.10.
Maybe this was an issue in 1.8 but i can't remember that i received any bugzilla report about.
But since 1.10 is released since several months, 1.8 won't get any updates anymore from our side. You should bother your distro to update to 1.10 ;)
If your distro maintainer don't want to update then he is reponsable to fix 1.8 packages.
So, without a confirmation that the issue exists with 1.10 the report is quite useless and only for the records.
Btw. did you file out a downstream report?

**Comment by Ryuno-Ki** [comment]
IIRC I did not. However, I close this issue and reopen if if I encounter it in Mate 1.10.
