### ISSUE TITLE
VLC loses focus on fullscreen after moving pointer

### ISSUE THREAD

**Issue by sean-v8** [mate-desktop/marco#514]
Been dealing with a frustrating issue since upgrading to more recent versions of the MATE desktop, surprised I haven't been able to find other reports as it's pretty annoying out of the box..

This behaviour only occurs with recent versions of Marco (regardless of compositor selection) and is not present when using Compiz on those same systems.

#### Expected behaviour
Keyboard controls shouldn't lose focus and become unusable when mouse is moved while playing full-screen video in VLC

#### Actual behaviour
Moving the mouse in full-screen mode causes a brief flicker of black followed by keyboard controls becoming unresponsive until focus is restored to the window again via clicking with the mouse.

I can confirm that this behaviour is present on:
- Ubuntu MATE 19.04 (Marco 1.20.3 + VLC 3.0.6)
- Ubuntu MATE 18.04.2 (Marco 1.20.1 + VLC 3.0.4)
- Debian 9 Stable w/ MATE (Marco 1.16.1 + VLC 3.0.4)

I can also confirm that this behaviour is absent on:
- Ubuntu MATE 16.04.6 (Marco 1.12.1 + VLC 2.2.2)
- Ubuntu MATE 19.04 (Compiz 0.9.14.0 + VLC 3.0.4)
- Debian 9 Stable w/ Gnome (Mutter 3.22.3 + VLC 3.0.4)

#### Steps to reproduce the behaviour
1) Ensure Marco window manager enabled
2) Play video in VLC
3) Enter full-screen mode
4) Move mouse around a bit
5) Attempt to use hotkeys (space-bar, Ctrl+Up etc)

#### MATE general version
1.20.4

#### Package version
1.20.3

#### Linux Distribution
Ubuntu MATE 19.04

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu-mate/+bug/1813203

**Comment by vkareh** [comment]
I think you will need to report this to [launchpad](https://bugs.launchpad.net/ubuntu-mate) (and post the link in your report) as well, since VLC is not part of MATE, but ships with Ubuntu MATE.

**Comment by sean-v8** [comment]
Cool, yeah I really didn't where to post this as it's mostly a VLC issue but seems to be pretty marco-specific.. edited my report here to reference an existing bug report over at launchpad, not really sure at this point whose yard this falls in as the OP there reported the bug's absence with VLC 3.0.3..

**Comment by vkareh** [comment]
Interesting! Thanks, that's helpful. I wonder what changed in VLC that marco needs to account for. We do some strange things with certain keybindings and pointer events...

Just occurred to me whether VLC supports gestures of some sort and whether marco is trying to grab the pointer when it receives gesture events, and doesn't release the pointer grab until you switch focus back to VLC... (Sorry, I'm just thinking out loud to determine where to start looking)

**Comment by sean-v8** [comment]
Awesome, really appreciate the assistance man!

I've been itching to upgrade my media center from 16.04 and this is the only thing that's been holding me back, praying it gets sorted out..

**Comment by waynec123** [comment]
Here are a few more details about this issue; I reported it on the linuxmint/mint19.2-beta project, [https://github.com/linuxmint/mint19.2-beta/issues/74](url)  a few days ago, but that project is a temporary bug squashing forum for the current Linux Mint 19.2 Beta release; I don't know how long it will remain active, so I will repeat some of the discussion from that report.

**Summary**
 There are two related issues, the first as described above by @sean-v8, and a related VLC fullscreen controller visibility issue.  Both are triggered by a single commit in VLC between versions 3.0.3 and 3.0.4; however only MATE/marco seems to exhibit the unexpected behaviour.  Whether this is a bug or a subtle difference in interpretation between the various window managers (and VLC), I can't say.
I use Linux Mint MATE edition, so my testing is on various versions of Mint MATE, Cinnamon, and Xfce, and my past experience is with Mint MATE.

**Details**

Two related bugs:

  1.  When playing a video with vlc, in fullscreen mode ("f" command, not F11 "Fullscreen Interface" mode), vlc loses input focus when the mouse is moved, causing it to ignore keyboard commands until a mouse click restores input focus. (This is what sean-v8 reported).
 2.    The vlc fullscreen controller is supposed to appear on the screen when the mouse is moved, stay there while the mouse is moving, and go away when the mouse is stationary; instead, it appears very briefly when the mouse stops moving, and only stays visible if you then manage to do a little dance with the mouse in the moment it appears.

**To Reproduce Issue 1**
Steps to reproduce the keyboard focus issue:  @sean-v8 has ably described this above; my observations are identical.

**To Reproduce Issue 2**
Steps to reproduce the  fullscreen controller not appearing issue:

1.    Play any video with the vlc player.
2.    Use the "f" keyboard command to put vlc into fullscreen mode. Do not use the F11 "Fullscreen Interface" command.
3.    Move the mouse; notice that there is a slight flicker, no fullscreen controller interface appears at the bottom of the screen.
4.    Stop moving the mouse. A fullscreen controller interface appears very briefly at the bottom of the screen. If you resume moving the mouse in the brief moment the interface is visible, it will stay visible as long as you keep the mouse moving; you can then move the cursor to the interface and use the controls on it. When the mouse cursor is on the visible fullscreen interface, keyboard commands will again function.

**Expected behaviour**
The vlc fullscreen controller is supposed to appear on the screen when the mouse is moved, stay there while the mouse is moving, and go away shortly after the mouse ceases moving (if the mouse has not been moved to the controller). If the mouse has been moved to the controller, it stays visible.

I am reasonably certain that both issues are caused by a single commit in VLC between versions 3.0.3 and 3.0.4 (see below).   I have not seen this behaviour with any version of VLC prior to 3.0.3, and I have used MATE and VLC for quite a few years, going back to at least Mint 15.  I first saw this when I installed Mint 19.1 (MATE / marco 1.20; Ubuntu 18.04 LTS base) earlier this year.  At the time, I found a discussion on the videolan forums of a similar issue, and following the suggestion there, downgraded VLC from 3.0.4 to 3.0.3, which fixed both issues.  Downgrading VLC is no longer an option for either workaround or testing, since the current VLC, 2.0.7 has replaced all previous versions in the bionic repository.

The following other non-MATE, non-marco window managers do not show these issues:

- Mint 19.1 Cinnamon
- Mint 19.2 Beta Cinnamon
- Mint 19.2 Beta Xfce

I can't really test compiz on Mint MATE since I don't know how to switch to it; I have not seen a preferences option to switch the actual window manager, just one to enable compositing in marco.  All tests with the current VLC, 2.0.7; I can no longer easily test VLC 3.0.3 and earlier with Cinnamon or Xfce.

The following two threads on the videolan forum mention what appears to be the same issue:

- [VLC 3.0.4 fullscreen bug (Ubuntu 18.04)](https://forum.videolan.org/viewtopic.php?t=147281)
- [[3.0.6] Losing focus in fullscreen, hotkeys won't work until clicking](https://forum.videolan.org/viewtopic.php?t=148827)

The first of these had one user narrowing the issue to a single commit in vlc:
[http://git.videolan.org/?p=vlc.git;a=commit;h=d60312d3ad4c4e27f3455b4f579999b826d3948c](http://git.videolan.org/?p=vlc.git;a=commit;h=d60312d3ad4c4e27f3455b4f579999b826d3948c)

Here is the offending commit, with the context diff:

```
gui: qt: prevent fullscreen controller from stealing focus
author	Filip Roséen <filip@atch.se>	
	Sun, 15 Jul 2018 20:26:30 -0700 (05:26 +0200)
committer	Hugo Beauzée-Luyssen <hugo@beauzee.fr>	
	Wed, 18 Jul 2018 09:33:57 -0700 (18:33 +0200)

A widget will (per default) receive focus when it is displayed,
something which is not ideal for our fullscreen controller (as it may
result in VLC grabbing focus from whatever window the user is actually
interested in at the time).

fixes #8712

Signed-off-by: Hugo Beauzée-Luyssen <hugo@beauzee.fr>
modules/gui/qt/components/controller.cpp

diff --git a/modules/gui/qt/components/controller.cpp b/modules/gui/qt/components/controller.cpp
index 04926a2..254ded0 100644 (file)
--- a/modules/gui/qt/components/controller.cpp
+++ b/modules/gui/qt/components/controller.cpp
@@ -806,7 +806,8 @@ FullscreenControllerWidget::FullscreenControllerWidget( intf_thread_t *_p_i, QWi
 
     vout.clear();

-    setWindowFlags( Qt::ToolTip );
+    setWindowFlags( Qt::Tool | Qt::FramelessWindowHint );
+    setAttribute( Qt::WA_ShowWithoutActivating );
     setMinimumWidth( FSC_WIDTH );
     isWideFSC = false;
 ```
I rebuilt the current vlc 2.0.7 from the source repository, confirmed that the issue was still there, then reversed this commit in the `controller.cpp` file, and rebuilt it again.  That version, with that small change of reversing this commit, no longer shows either issue.  Built and tested on Mint 19.1 MATE (MATE / Marco 1.20).

 I do not have any experience with Qt, so I have no idea why this commit affected Marco and not Cinnamon and Xfce window managers.  @gm10 thought that this commit was submitted to fix a similar bug against most other window managers for VLC.  I have not yet been able to test this rebuilt version of VLC against Cinnamon and Xfce window managers to see whether it fixed anything with them, since my first attempts to make a `.deb` package to install on my other test installs didn't quite work.  I need to do some more homework in the package building area. 

I apologize for the length of this; I hope this helps narrow things down a bit.

**Comment by SkewedZeppelin** [comment]
relevant #151 ?

**Comment by gm10** [comment]
Maybe, although unlike that one, the issue here is limited to VLC only. All other Qt5 apps that I have including other Qt5 video players or even just VirtualBox do show fullscreen controls just fine without stealing focus. I don't know enough about this to say whether the bug is with VLC, Qt5 or Marco.

Just to confirm that this is also happening with the git master version of Marco, also with Metacity, both on an 18.04 base (Qt5.9.5) and a 19.04 base (Qt5.12).

**Comment by rcaridade145** [comment]
@vkareh

 The explanation of the QT flags can be found here https://stackoverflow.com/questions/966688/show-window-in-qt-without-stealing-focus

The commit on Metacity where this issue was considered : https://gitlab.gnome.org/GNOME/metacity/-/commit/186b2b7851208afb52b5239a36a86620d2fcd5c4

**Comment by raveit65** [comment]
Fixed.
https://github.com/mate-desktop/marco/commit/6ea23df6aa8a42973a1bb42c5c618b322d47488e
https://github.com/mate-desktop/marco/commit/634057c2feed37d466d0740df32ff38fb2f5cfe1

**Comment by augnustin** [comment]
I'm happy to read the issue is fixed, but how can we enjoy the fix? What should we upgrade? I'm using Linux Mint 19.1 Tessa.

Cheers

**Comment by samuel-phan** [comment]
I'm using Linux Mint 20.3 Una, and I confirm that this issue is fixed.
MATE 1.26.0

From the fix commit https://github.com/mate-desktop/marco/commit/6ea23df6aa8a42973a1bb42c5c618b322d47488e and https://github.com/mate-desktop/marco/commit/634057c2feed37d466d0740df32ff38fb2f5cfe1, it seems that it is tagged as part of MATE 1.26.0 and 1.25.1, so I guess you need to have at least these MATE versions to have the fix.

**Comment by augnustin** [comment]
Thanks for getting back. I did upgrade to Mint 20.3 and the problem seems to be fixed! :tada:
