### ISSUE TITLE
[REG 1.22.1->1.22.2] No longer possible to go "exclusive" full screen

### ISSUE THREAD

**Issue by zaps166** [mate-desktop/marco#540]
#### Expected behaviour
- disable compositor (or use compositor which doesn't redirect full screen windows),
- only one screen is connected,
- fullscreen OpenGL or Vulkan apps runs in page flipping mode,

#### Actual behaviour
- disable compositor (or use compositor which doesn't redirect full screen windows),
- only one screen is connected,
- fullscreen OpenGL or Vulkan apps runs in blit mode (it is slower and can cause screen tearing even if v-sync is enabled),

#### Steps to reproduce the behaviour
- disable compositor,
- if you use NVIDIA proprietary drivers, open `nvidia-settings`->"OpenGL settings" and check "Enable Graphics API Visual Indicator" - this allows you to easily check the "Flip" mode at runtime,
- be sure that you have single only one connected,
- run OpenGL or Vulkan application on fullscreen (e.g. game or video player),
- notice that NVIDIA Visual Indicator still displays "Blit" instead of "Flip" (in left-top corner). It is difficult to observe w/o NVIDIA indicator, but you can see lower performance or higher power consumption or sometimes screen tearing even is v-sync is enabled.

#### MATE general version
1.22.1

#### Package version
community/marco 1.22.2-1 (mate)

#### Linux Distribution
Manjaro Linux

#### Link to downstream report of your Distribution

---

Reverting commit fa32fffe0f6b0191cd17ce9ab19f89c4082497cf fixes the issue. AFAIK transparent windows (even if alpha is 0xff) won't allow flipping mode.

---

You can try (full screen) on mpv, QMPlay2, glxgears, [Vulkan examples](https://github.com/SaschaWillems/Vulkan), some Steam games like RoTR (but not all games), etc...

`glxgears -fullscreen` works, but running `glxgears` and then going full screen by a key shortcut does not.

**Comment by lukefromdc** [comment]
Do you know if this is Nvidia-only or occurs with other drivers? You should be able test on your hardware with Nouveau or even llvmpipe to find out.

**Comment by zaps166** [comment]
It is driver Independent, tested also on Mesa AMD driver, compositor disabled:
- marco 1.22.1 - screen tearing not observed,
- marco 1.22.2 - screen tearing observed,

Moreover [qdre-compositor](https://gitlab.com/zaps166/qdre/tree/master/qdre-compositor) is unable to unredirect full screen windows in marco 1.22.2, but it does in marco 1.22.1 and in other WMs like openbox.

**Comment by lukefromdc** [comment]
OK, that is settled. I don't know a whole lot about this (most of my WM work has been on compiz)
but the commit you mentioned
involves making something transparent, which should not be possible between two
different windows on x11 in thr absence of transparency. My guess is drivers are detecting
this and it is triggering a composited codepath.

**Comment by zaps166** [comment]
Ok, is it possible to fix?

- If Marco doesn't need this feature, it can be reverted.
- If Marco needs it (maybe for semi-transparent styles?), let's try to disable transparency on borderless (including full screen) windows. Or use this only for build-in compositor (notice, that external compositors can unredirect window at any time especially full screen windows).

**Comment by raveit65** [comment]
This commit was part of invisible borders PR and i don't know if this can be reverted without loosing invisible borders, which was a bugfix to improve resizing windows if compositor is used.
Why you don't use this improvement and compositor?
Old box?
Well, i am using latest nvidia driver, i can try to reproduce it in the next weeks when i find time.
Which monitor resolution do you use?
I ask because i see always see tearing effect with nvidia and all marco/metacity versions in fullscreen the last 10-15 years on linux ;)

Btw. can you reproduce the problem with metacity?
It is possible to use metacity without compositor.

**Comment by zaps166** [comment]
> I ask because i see always see tearing effect with nvidia and all marco/metacity versions in fullscreen the last 10-15 years on linux ;)

If you use compositor on marco you'll get always tearing on Intel "modesetting" driver and on nvidia proprietary driver, because both of them don't properly support the X11 Present extension which marco uses. In this case compositor **must** use OpenGL. X11 Present extension works properly on AMD drivers and Intel "intel" driver and probably on nouveau drivers :)

When no compositor is enabled, full screen OpenGL/Vulkan apps with V-Sync enabled and when only a single monitor is connected won't tear (except on marco 1.22.2).

---

On nvidia proprietary drivers you must have "Allow Flipping" enabled in `nvidia-settings`. This settings is enabled by default. And an advice - don't use "Force Composition Pipeline", because it add a minimum lag to mouse cursor :smile: (maybe it uses software cursor like Wayland?)

---

> Why you don't use this improvement and compositor?

I've written and now I use qdre-compositor, because it can use both OpenGL and X11 Present for V-Sync and it can unredirect full screen apps for better performance (which is impossible on marco 1.22.2).

Un-redirecting full screen windows (depends on compositor settings) can reduce GPU (and also CPU) usage causing e.g. longer battery life, lower temperature, etc.

---

I don't own G-Sync monitor and I don't have any knowledge of this technology, but there is possibility that it can't be now used with marco...

---

> Btw. can you reproduce the problem with metacity?

```
$ pacman -Q metacity
metacity 3.32.0-1
```

Hmm. It works. I've got `Failed to create MetaCompositorXRender: Another compositing manager is running on screen 0` because `qdre-compositor` is running. Full screen works properly in this case. Maybe metacity got some additional fixes after https://gitlab.gnome.org/GNOME/metacity/commit/74db1f11?

**Comment by raveit65** [comment]
> X11 Present extension works properly on AMD drivers and Intel "intel" driver and probably on nouveau drivers :)

I am sorry to say but using nouveau on actual nvidia cards isn't fun ;)
Except you like glitches, flickering colors and a slow starting X or wayland.
In other words the desktop is unusable.
It has a reason that fedora gnome-shell ships a repo with nvidia driver.

**Comment by zaps166** [comment]
> and probably on nouveau drivers

I wrote "probably", because I don't know, because I don't use them :)

**Comment by zaps166** [comment]
Probably this commit fixed the issue in metacity: https://gitlab.gnome.org/GNOME/metacity/commit/5863176a2bd659c8d9a3d1c7b023a27c1a8c0aa5

**Comment by lukefromdc** [comment]
The invisible border stuff is supposed to run ONLY in the composited codepath as far as I know, since it is not possible to render a transparent window or portion therof over another in x11 without compositing. Any part of this running when the compositor is turned off is presumably a mistake. The metacity commit 
https://gitlab.gnome.org/GNOME/metacity/commit/5863176a2bd659c8d9a3d1c7b023a27c1a8c0aa5
"frame: always use the client window's visual" essentially shoulod prevent the code used in https://github.com/mate-desktop/marco/commit/fa32fffe0f6b0191cd17ce9ab19f89c4082497cf "frame: make frame window transparent " from unconditionally forcing an RBGA window, which the driver presumably is catching and going to its composited codepath.

**Comment by raveit65** [comment]
@zaps166 
Did you try out the metacity commit?

**Comment by zaps166** [comment]
@raveit65 Yes, with metacity commit now full screen works properly, but it looks like it reverts the fa32fff.

**Comment by raveit65** [comment]
Ok, we need to wait that marco maintainer will find some time for it.

**Comment by zaps166** [comment]
Ok, thanks!

**Comment by lukefromdc** [comment]
A build of marco with https://gitlab.gnome.org/GNOME/metacity/commit/5863176a2bd659c8d9a3d1c7b023a27c1a8c0aa5 applied( and with --disable-verbose to stop an undefined symbol error after latest Debian Unstable changes) ran fine, resizing from shadow area with compositing worked fine, and I didn't notice any black frames without compositing, so it looks like the shadow resize area (if this is the frame) gets the correct width of zero with compositing turned off and the proposed fix can be safely applied.

Didn't get any problems running compiz-reloaded against this either.

**Comment by lukefromdc** [comment]
This is not quite a revert of https://github.com/mate-desktop/marco/commit/fa32fffe0f6b0191cd17ce9ab19f89c4082497cf as the `visual = NULL` case is taken out, the special case for depth 32 windows (assume them RBGA) is removed too,  and the system visual is always used.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/marco/pull/545 applies the metacity commit in question "frame: always use the client window's visual "

**Comment by muktupavels** [comment]
> AFAIK transparent windows (even if alpha is 0xff) won't allow flipping mode.

> Moreover qdre-compositor is unable to unredirect full screen windows

Do you have more info? How/why unredirection does not work with argb windows?

**Comment by zaps166** [comment]
> How/why unredirection does not work with argb windows?

If ARGB window has alpha channel below 0xff, unredirected window won't display transparency. Moreover driver won't optimise it anyway, screen tearing will be visible even with V-Sync and performance will be lower anyway (blit mode).

Without compositor results are the same like unredirected window.

**Comment by lukefromdc** [comment]
I am pretty sure that to unredirect a window or to pageflip with it in the video RAM, everything in it has to be supported by the monitor, which has red, green, and blue (RGB) channels.  All subpixels transparent is white, all subpixels opaque is black, and intermediate values give colors and greyscales.   An alpha value here could only mean "show me what is BEHIND the monitor" as turning the RBG channels transparent already means white or "show me the backlight."

An alpha value for a monitor actually would have a use case for "augmented reality" or AR headsets and could be implemented by optically "composting" each pixil with a fiber optic fiber from a camera lens behind the monitor with an electrically variable beamsplitter for each pixel ($$$). Much cheaper  to add a normal video camera and composit your AR windows onto it in the normal fashion and send that to a normal LCD screen bought from the lowest bidder. 

To feed that same RGBA video image without modification to your desktop monitor would require that the monitor itself have code to throw out the alpha channel instead of say, overflowing a buffer with it by writing four elements into a three element structure. To do this in the video driver (with new code) would of course be possible, but you would still be wasting RAM by writing 4 elements when the 4th will just be discarded. Thus we only pageflip 3 channel video, sending it to a screen that displays 3 channels red, green, and blue and from them mixes all the colors we see on the screen.

**Comment by zaps166** [comment]
Now I noticed that after this fix everything runs much faster no matter if compositor is enabled or not - I can smoothly play 4k 60FPS videos again on integrated Intel/AMD GPUs.
